name: Publish Image

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.6
      - run: ko build --bare
